branches:
  except: "/^v\\d/"
addons:
  apt:
    packages: rpm
before_install: gem install fpm
script:
  - make deb
  - make rpm
before_deploy: |
  if [ -z "$(git tag --list "v$(make version)")" ]; then \
      git config --local user.name "bot50"; \
      git config --local user.email "bot@cs50.harvard.edu"; \
      git tag "v$(make version)"; \
  fi
deploy:
  # Ubuntu
  # 12.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/precise"

  # 12.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/quantal"

  # 13.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/raring"

  # 13.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/saucy"

  # 14.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/trusty"

  # 14.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/utopic"

  # 15.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/vivid"

  # 15.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"    dist: "ubuntu/wily"

  # 16.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/xenial"

  # 16.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/yakkety"

  # 17.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/zesty"

  # 17.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/artful"

  # 18.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/bionic"

  # 19.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/disco"

  # 19.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/eoan"

  # 20.04
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/focal"

  # 20.10
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    local-dir: "build/deb"
    dist: "ubuntu/groovy"

  # Fedora
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/24"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/25"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/26"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/27"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/28"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/29"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/30"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/31"
  - provider: packagecloud
    username: cs50
    repository: repo
    token: $PACKAGECLOUD_TOKEN
    skip_cleanup: true
    on:
      branch: master
    dist: "fedora/32"

  # GitHub release
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master
notifications:
  slack:
    secure: ISOGlNSGXOrMBrKTnjTWQXVjjoBn78++xF1mUv/PYZxn3J4L4WpybLLjAuBENsD7YeHSaXUnSbIV5mDzlx5Q1cyrS+auGOHqi5xGV01zNBB1Fig1SkUf7zJS8KyjiPKyi+DexnTt1BY4xaA1uGzq9hoGZEPXKHNlz4v1I6f6fHQ=
